services:
  - type: web
    name: travelpayouts-rotator
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: YOURLS_API_URL
        sync: false
      - key: YOURLS_SIGNATURE_TOKEN
        sync: false 